// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjEijdcrmuIo0OA45kZsWz7wCP-dXp5lU',
    appId: '1:89109549786:web:adbe198fbef818d8cacbe3',
    messagingSenderId: '89109549786',
    projectId: 'medsync-252fe',
    authDomain: 'medsync-252fe.firebaseapp.com',
    storageBucket: 'medsync-252fe.firebasestorage.app',
    measurementId: 'G-8S64BEQYV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6SK1yTpnFKyiy47j1O-8CtxMpp1p1PNw',
    appId: '1:89109549786:android:dc18be68b54aa60ecacbe3',
    messagingSenderId: '89109549786',
    projectId: 'medsync-252fe',
    storageBucket: 'medsync-252fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwdZ2spNqvkMYlS4eO8Ww-RMxUI-yBa2k',
    appId: '1:89109549786:ios:bee65c90791b514ecacbe3',
    messagingSenderId: '89109549786',
    projectId: 'medsync-252fe',
    storageBucket: 'medsync-252fe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwdZ2spNqvkMYlS4eO8Ww-RMxUI-yBa2k',
    appId: '1:89109549786:ios:bee65c90791b514ecacbe3',
    messagingSenderId: '89109549786',
    projectId: 'medsync-252fe',
    storageBucket: 'medsync-252fe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjEijdcrmuIo0OA45kZsWz7wCP-dXp5lU',
    appId: '1:89109549786:web:e79bb4565ba9d91bcacbe3',
    messagingSenderId: '89109549786',
    projectId: 'medsync-252fe',
    authDomain: 'medsync-252fe.firebaseapp.com',
    storageBucket: 'medsync-252fe.firebasestorage.app',
    measurementId: 'G-X5YH66Q8T3',
  );
}
